# SPDX-License-Identifier: MIT
"""Parser for text files generated by MC_Buster and MM_Buster."""
import logging
import re
from typing import Iterator, List, Optional

from .base import BaseIngredientParser, BaseRecipeParser
from .models import Ingredient, Recipe
from .registry import ParserRegistry

logger = logging.getLogger(__name__)


@ParserRegistry.register
class BusterParser(BaseRecipeParser):
    """Parser for Buster text format (MC_Buster / MM_Buster)."""

    _CONTINUATION_HYPHEN_RE = re.compile(r"^\s*-(?!-)\s*(.*)$")
    _CONTINUATION_SEMI_RE = re.compile(r"^\s*1\s*;\s*(.*)$")
    _FOOTER_MARKERS_RE = re.compile(
        r"^\s*(?:"
        r"Converted by M[CM]_Buster"
        r"|SHARED BY:"
        r"|Recipe by:"
        r"|Contributor:"
        r"|Preparation Time:"
        r"|PER\s+SERV(?:ING|lNG)?(?:\s*\(|:)"
        r"|Food Exchanges:"
        r"|Yield:\s*\d+"
        r"|By\s+\"[^\"]+\"\s+<[^>]+>"
        r"|[-=_ ]{5,}$"
        r"|═{5,}"
        r"|(?:VEGAN|\d+\s+SERVINGS\s+VEGAN)$"
        r"|(?:From rec\.food|REC\.FOOD\.RECIPES)"
        r")",
        re.IGNORECASE,
    )

    def __init__(self, ingredient_parser: BaseIngredientParser):
        super().__init__(ingredient_parser)
        self.source_format = "Buster"

    @classmethod
    def format_id(cls) -> str:
        return "buster"

    @classmethod
    def aliases(cls) -> list[str]:
        return ["mc_buster", "mm_buster"]

    @classmethod
    def priority(cls) -> int:
        return 20

    @classmethod
    def supported_extensions(cls) -> set[str]:
        return {".mxp", ".txt"}

    @classmethod
    def detect(cls, filepath: str, content_sample: str) -> float:
        if not content_sample:
            return 0.0

        if (
            "Converted by MC_Buster" in content_sample
            or "Converted by MM_Buster" in content_sample
        ):
            return 0.99

        # Fallback: "Title: " and "Ingredients" and "Instructions" text structure (confidence 0.50)
        if (
            re.search(r"^\s*Title:\s+", content_sample, re.MULTILINE | re.IGNORECASE)
            and re.search(r"^\s*Ingredients\b", content_sample, re.MULTILINE | re.IGNORECASE)
            and re.search(r"^\s*Instructions\b", content_sample, re.MULTILINE | re.IGNORECASE)
        ):
            return 0.50

        return 0.0

    def parse_content(self, content: str, filepath: str = "") -> Iterator[Recipe]:
        """Parse Buster format content and yield Recipe objects."""
        lines = content.splitlines()

        current_recipe: Optional[Recipe] = None
        section: Optional[str] = None  # "header", "ingredients", "instructions", "footer"
        current_ingredient_parts: List[str] = []
        instruction_paragraphs: List[List[str]] = []
        current_instruction_lines: List[str] = []

        def flush_ingredient():
            nonlocal current_ingredient_parts
            if not current_ingredient_parts or not current_recipe:
                return
            combined = " ".join(part.strip() for part in current_ingredient_parts if part.strip())
            current_ingredient_parts = []
            if not combined:
                return
            ing = (
                self.ingredient_parser.parse(combined)
                if self.ingredient_parser
                else Ingredient(raw=combined)
            )
            current_recipe.ingredients.append(ing)

        def flush_instructions():
            nonlocal current_instruction_lines, instruction_paragraphs
            if not current_recipe:
                return
            if current_instruction_lines:
                instruction_paragraphs.append(current_instruction_lines)
                current_instruction_lines = []
            for para in instruction_paragraphs:
                text = " ".join(line.strip() for line in para if line.strip())
                if text:
                    current_recipe.instructions.append(text)
            instruction_paragraphs = []

        def finalize_recipe() -> Optional[Recipe]:
            nonlocal current_recipe, section
            if not current_recipe:
                return None
            flush_ingredient()
            flush_instructions()
            rec = current_recipe
            current_recipe = None
            section = None
            return rec

        for line in lines:
            # Check for new recipe start
            title_match = re.match(r"^\s*Title:\s*(.*)$", line, re.IGNORECASE)
            if title_match:
                rec_to_yield = finalize_recipe()
                if rec_to_yield and rec_to_yield.title:
                    yield rec_to_yield

                current_recipe = Recipe(
                    title=title_match.group(1).strip(),
                    source_file=filepath,
                    source_format=self.source_format,
                )
                section = "header"
                current_ingredient_parts = []
                instruction_paragraphs = []
                current_instruction_lines = []
                continue

            if not current_recipe:
                # Still before the first Title: line
                continue

            if section == "header":
                yield_match = re.match(r"^\s*Yield:\s*(.*)$", line, re.IGNORECASE)
                if yield_match:
                    current_recipe.yield_amount = yield_match.group(1).strip()
                    continue

                if re.match(r"^\s*Ingredients\b", line, re.IGNORECASE):
                    section = "ingredients"
                    continue

            elif section == "ingredients":
                if re.match(r"^\s*Instructions\b", line, re.IGNORECASE):
                    flush_ingredient()
                    section = "instructions"
                    continue

                stripped = line.strip()
                if not stripped:
                    continue

                # Check funky continuation rules
                hyphen_match = self._CONTINUATION_HYPHEN_RE.match(line)
                semi_match = self._CONTINUATION_SEMI_RE.match(line)

                if (hyphen_match or semi_match) and current_ingredient_parts:
                    cont_text = hyphen_match.group(1) if hyphen_match else semi_match.group(1)
                    current_ingredient_parts.append(cont_text)
                else:
                    flush_ingredient()
                    current_ingredient_parts.append(stripped)

            elif section == "instructions":
                if self._FOOTER_MARKERS_RE.match(line):
                    flush_instructions()
                    section = "footer"
                    continue

                stripped = line.strip()
                if not stripped:
                    if current_instruction_lines:
                        instruction_paragraphs.append(current_instruction_lines)
                        current_instruction_lines = []
                else:
                    current_instruction_lines.append(stripped)

            elif section == "footer":
                # Wait for next Title: or EOF
                continue

        final_rec = finalize_recipe()
        if final_rec and final_rec.title:
            yield final_rec
